// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrifxyyxdnmwwimcxkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaWZ4eXl4ZG5td3dpbWN4a2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDk5MjEsImV4cCI6MjA3MDU4NTkyMX0.gOw9eKdziRrSR4zv1ly6hv0ZOod2Cnv9D8_jWJ3IZwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});